### ISSUE TITLE
NoSuchMethodError: breeze.linalg.DenseVector when running spectrallda-tensor_2.11-1.0.jar

### ISSUE THREAD

**Issue by chaomai** [Mega-DatA-Lab/SpectralLDA-Spark#1]
## 1. environment

* Spark 2.1.0
* sbt 0.13
* Scala 2.11.8
* Java 1.8.0_112

## 2. issue

When I run the example call,

```
spark-submit --packages com.github.scopt:scopt_2.11:3.5.0 \
--class edu.uci.eecs.spectralLDA.SpectralLDA \
target/scala-2.11/spectrallda-tensor_2.11-1.0.jar \
-k 5 --alpha0 5.0 --input-type libsvm -o results \
src/main/resources/Data/datasets/synthetic/samples_train_libsvm.txt
```

I got this exception,

```
Exception in thread "main" java.lang.NoSuchMethodError: breeze.linalg.DenseVector$.canSetD()Lbreeze/generic/UFunc$InPlaceImpl2;
        at edu.uci.eecs.spectralLDA.utils.RandNLA$$anonfun$randomProjectM2$3.apply(RandNLA.scala:150)
        at edu.uci.eecs.spectralLDA.utils.RandNLA$$anonfun$randomProjectM2$3.apply(RandNLA.scala:149)
        ......
```

### add breeze and breeze-natives as dependencies

I find the breeze and breeze-natives are commented out in `build.sbt`, so I uncommented and add them as dependencies. But actually it's unable to build the `spectrallda-tensor_2.11-1.0.jar`. Following error is thrown when building,

```
[error] ....../src/main/scala/edu/uci/eecs/spectralLDA/algorithm/ALS.scala:123: value toDenseVector is not amember of breeze.linalg.Transpose[breeze.linalg.DenseVector[Double]]
[error]     val lambda = norm(updatedA(::, *)).toDenseVector
```

### using newer version of breeze and breeze-natives

Also won't work. 

Please help me figure out the problem of this issue.
Thank you

**Comment by jli05** [comment]
We avoided declaring Breeze as dependency for the very reason that Spark has dependencies on it and we wanted to avoid any version issues; but on the other hand it's at Spark's discretion to refactor/remove its dependency on Breeze from any version on.

See if you can compile a fresh copy of Spark 2.1.0 linked with native BLAS/LAPACK lib following the instructions in the `README` of the project. If you cannot, a temporary solution is to use Spark 2.0.x, which was known to work with this project. It's still recommended to compile Spark from the source following the instructions in `README` of this project.

**Comment by chaomai** [comment]
I tried the spark-2.0.2 and it works.

Thank you!

**Comment by jli05** [comment]
It should work with Spark 2.1.1 now. Please let us know if any problem.
